apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: build-ui
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
    creationTimestamp: null
    generation: 1
    labels:
      build: build-ui
    name: build-ui
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: docker-registry.default.svc:5000/hygieia/build-ui:latest
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: ui
    name: build-ui
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: build-ui:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: /UI
      git:
        ref: override-default-nginx-conf
        uri: https://github.com/tomgeorge/Hygieia
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: nodejs:8
          namespace: openshift
      type: Source
    triggers:
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange
    - generic:
        secret: 019d3db99764e75e
      type: Generic
    - github:
        secret: dca9639337f3d252
      type: GitHub
  status:
    lastVersion: 0
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      labels:
        build: ui
    name: ui
    spec:
      lookupPolicy:
        local: false
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: ui
    name: ui
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: ui:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      images:
      - as: null
        from:
          kind: ImageStreamTag
          name: build-ui:latest
        paths:
        - destinationDir: .
          sourcePath: /opt/app-root/src/dist/.
        - destinationDir: ./nginx-default-cfg
          sourcePath: /opt/app-root/src/docker/api.conf
        - destinationDir: ./nginx-start
          sourcePath: /opt/app-root/src/docker/substitute-nginx-proxy-pass.sh
      type: Image
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: nginx:latest
          namespace: openshift
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers:
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange
    - generic:
        secret: 767b7d2dbfffde5d
      type: Generic
    - github:
        secret: 1ba0322210651c63
      type: GitHub
  status:
    lastVersion: 0
