apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: deployment-api
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    generation: 1
    labels:
      app: api
    name: api
  spec:
    replicas: 1
    selector:
      deploymentconfig: api
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: api
          deploymentconfig: api
      spec:
        containers:
        - env:
          - name: JAVA_APP_JAR
            value: api.jar
          - name: DBHOST
            value: mongodb
          - name: DBNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-persistent-k68xt-credentials-j2qp5
                key: database_name
          - name: DBUSERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-persistent-k68xt-credentials-j2qp5
                key: username
          - name: DBPASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-persistent-k68xt-credentials-j2qp5
                key: password
          image: api:latest
          imagePullPolicy: Always
          name: api
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          - containerPort: 8778
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - api
        from:
          kind: ImageStreamTag
          name: api:latest
          namespace: hygieia
      type: ImageChange
    - type: ConfigChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
