apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: hygieia-jenkins-build-collector
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
    creationTimestamp: null
    generation: 1
    labels:
      build: hygieia-jenkins-build-collector
    name: hygieia-jenkins-build-collector
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: docker-registry.default.svc:5000/hygieia/hygieia-jenkins-build-collector:latest
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: hygieia-jenkins-build-collector
    name: hygieia-jenkins-build-collector
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: hygieia-jenkins-build-collector:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: /collectors/build/jenkins
      git:
        ref: jenkins-oauth-support
        uri: https://github.com/tomgeorge/Hygieia
      type: Git
    strategy:
      dockerStrategy:
        dockerfilePath: docker/Dockerfile
    triggers:
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange
    - generic:
        secret: 019d3db99764e75e
      type: Generic
    - github:
        secret: dca9639337f3d252
      type: GitHub
  status:
    lastVersion: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    generation: 1
    labels:
      app: hygieia-jenkins-build-collector
    name: hygieia-jenkins-build-collector
  spec:
    serviceName: jenkins
    replicas: 1
    selector:
      deploymentconfig: hygieia-jenkins-build-collector
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: hygieia-jenkins-build-collector
          deploymentconfig: hygieia-jenkins-build-collector
      spec:
        serviceAccountName: jenkins
        containers:
        - env:
          - name: DBNAME
            valueFrom:
              secretKeyRef:
                key: database-name
                name: mongodb
          - name: DBPASSWORD
            valueFrom:
              secretKeyRef:
                key: database-password
                name: mongodb
          - name: DBHOST
            value: mongodb.${NAMESPACE}.svc
          - name: JENKINS_CRON
            value: '5 * * * * *'
          - name: JENKINS_SERVERS
            value: https://admin:password@jenkins-${NAMESPACE}.${OPENSHIFT_DEFAULT_SUBDOMAIN}
          - name: DBPORT
            value: "27017"
          - name: MONGO_PORT
            value: "27017"
          - name: DBUSERNAME
            valueFrom:
              secretKeyRef:
                key: database-user
                name: mongodb
          image: hygieia-jenkins-build-collector:latest
          imagePullPolicy: Always
          name: hygieia-jenkins-build-collector
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
parameters:
- name: NAMESPACE
- name: OPENSHIFT_DEFAULT_SUBDOMAIN
