apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: run-ui
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      labels:
        build: run-ui
    name: run-ui
    spec:
      lookupPolicy:
        local: false
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: ui
    name: run-ui
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: run-ui:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      images:
      - as: null
        from:
          kind: ImageStreamTag
          name: build-ui:latest
        paths:
        - destinationDir: .
          sourcePath: /opt/app-root/src/dist/.
        - destinationDir: ./nginx-default-cfg
          sourcePath: /opt/app-root/src/docker/api.conf
        - destinationDir: ./nginx-start
          sourcePath: /opt/app-root/src/docker/substitute-nginx-proxy-pass.sh
      type: Image
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: nginx:latest
          namespace: openshift
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers:
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange
    - generic:
        secret: 767b7d2dbfffde5d
      type: Generic
    - github:
        secret: 1ba0322210651c63
      type: GitHub
  status:
    lastVersion: 0
