apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: ui-route
objects:
- apiVersion: v1
  kind: Route
  metadata:
    name: ui-route
  spec:
    host: hygieia.${NAMESPACE}.${OPENSHIFT_DEFAULT_SUBDOMAIN}
    to:
      kind: Service
      name: ui-service
parameters:
- name: NAMESPACE 
- name: OPENSHIFT_DEFAULT_SUBDOMAIN
