k8s_namespace: hygieia
filter_tags: unpriv

openshift_cluster_content:
  - object: Admin-level setup
    content:
    - name: Configure Projects
      template: "{{ inventory_dir }}/../.openshift/templates/projects.yml"
      params_from_vars:
        NAMESPACE: "{{ k8s_namespace }}"
        DISPLAY_NAME: Hygieia Deployment
        OPENSHIFT_DEFAULT_SUBDOMAIN: "{{ openshift_default_subdomain }}"
      action: create
      tags:
        - priv
        - all
    - name: Apply policy objects
      template: "{{ inventory_dir }}/../.openshift/policy/"
      namespace: "{{ k8s_namespace }}"
      tags:
        - priv
        - all
  - object: Builds
    content:
    - name: API
      template: "{{ inventory_dir }}/../.openshift/templates/build-api.yml"
      namespace: "{{ k8s_namespace }}"
      tags:
        - unpriv
        - all
    - name: Audit API
      template: "{{ inventory_dir }}/../.openshift/templates/build-apiaudit.yml"
      namespace: "{{ k8s_namespace }}"
      tags:
        - unpriv
        - all
    - name: UI Builder and Runtime Images
      template: "{{ inventory_dir }}/../.openshift/templates/build-ui.yml"
      namespace: "{{ k8s_namespace }}"
      tags:
        - unpriv
        - all
  - object: Deployments
    content:
    - name: MongoDB
      template: "openshift//mongodb-persistent"
      action: create
      namespace: "{{ k8s_namespace }}"
      tags:
        - unpriv
        - all
    - name: Jenkins
      template: "openshift//jenkins-persistent"
      action: create
      namespace: "{{ k8s_namespace }}"
      tags:
        - unpriv
        - all
    - name: API
      template: "{{ inventory_dir }}/../.openshift/templates/deployment-api.yml"
      namespace: "{{ k8s_namespace }}"
      tags:
        - unpriv
        - all
    - name: Audit API
      template: "{{ inventory_dir }}/../.openshift/templates/deployment-apiaudit.yml"
      namespace: "{{ k8s_namespace }}"
      tags:
        - unpriv
        - all
    - name: UI
      template: "{{ inventory_dir }}/../.openshift/templates/deployment-ui.yml"
      namespace: "{{ k8s_namespace }}"
      params_from_vars:
        NAMESPACE: "{{ k8s_namespace}}"
      tags:
        - unpriv
        - all
    - name: Jenkins Collector
      template: "{{ inventory_dir }}/../.openshift/templates/hygieia-jenkins-build-collector-deployment.yml"
      namespace: "{{ k8s_namespace }}"  
      params_from_vars:
        NAMESPACE: "{{ k8s_namespace }}"
      tags:
        - unpriv
        - all
    - name: GitHub Collector
      template: "{{ inventory_dir }}/../.openshift/templates/hygieia-github-collector-deployment.yml"
      namespace: "{{ k8s_namespace }}"
      params_from_vars:
        NAMESPACE: "{{ k8s_namespace }}"
        GITHUB_PERSONAL_ACCESS_TOKEN: "{{ github_personal_access_token }}"
      tags:
        - unpriv
        - all
  - object: Services
    content:
    - name: UI Service
      template: "{{ inventory_dir }}/../.openshift/templates/ui-service.yml"
      namespace: "{{ k8s_namespace }}"
      tags:
        - unpriv
        - all
    - name: API Service
      template: "{{ inventory_dir }}/../.openshift/templates/api-service.yml"
      namespace: "{{ k8s_namespace }}"
      tags:
        - unpriv
        - all
  - object: Routes
    content:
    - name: UI Route
      template: "{{ inventory_dir }}/../.openshift/templates/ui-route.yml"
      params_from_vars:
        NAMESPACE: "{{ k8s_namespace }}"
        OPENSHIFT_DEFAULT_SUBDOMAIN: "{{ openshift_default_subdomain }}"
      namespace: "{{ k8s_namespace }}"
      tags:
        - unpriv
        - all
