---
openshift_cluster_content:
- object: projectrequest
  content:
  - name: gogs-project
    template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/v3.9.0/files/projectrequest/template.yml"
    template_action: create
    params: "{{ inventory_dir }}/../files/projectrequests/gogs"
- object: deployments
  content:
  - name: gogs
    namespace: gogs
    template: "{{ inventory_dir }}/../files/templates/gogs-persistent-template.yaml"
    params: "{{ inventory_dir }}/../files/params/gogs-params"
